# Generated by Django 4.2.11 on 2024-06-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='musgician',
            new_name='musician',
        ),
    ]
