# Generated by Django 4.2.11 on 2024-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='Phonenumber',
            field=models.IntegerField(),
        ),
    ]
